export const SET_SIZE = "SET_SIZE";
export const SET_OS = "SET_OS";
export const INCREASE_SCORE = "INCREASE_SCORE";
export const DECREASE_SCORE = "DECREASE_SCORE";
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
export const SET_REFEREE_DATA = "SET_REFEREE_DATA";
export const SET_CHECKED = "SET_CHECKED";
export const SET_TOURNAMENTS = "SET_TOURNAMENTS";
export const SET_SELECTED_TOURNAMENT = "SET_SELECTED_TOURNAMENT";
export const SET_CONTENTS = "SET_CONTENTS";
export const SET_SELECTED_CONTENT = "SET_SELECTED_CONTENT";
export const SET_MODE_HOME_PAGE = "SET_MODE_HOME_PAGE";







