export const countries = [
  { text: "Afghanistan", id: "AF", icon: "🇦🇫" },
  { text: "Albania", id: "AL", icon: "🇦🇱" },
  { text: "Algeria", id: "DZ", icon: "🇩🇿" },
  { text: "American Samoa", id: "AS", icon: "🇦🇸" },
  { text: "Andorra", id: "AD", icon: "🇦🇩" },
  { text: "Angola", id: "AO", icon: "🇦🇴" },
  { text: "Argentina", id: "AR", icon: "🇦🇷" },
  { text: "Armenia", id: "AM", icon: "🇦🇲" },
  { text: "Australia", id: "AU", icon: "🇦🇺" },
  { text: "Austria", id: "AT", icon: "🇦🇹" },
  { text: "Azerbaijan", id: "AZ", icon: "🇦🇿" },
  { text: "Bahrain", id: "BH", icon: "🇧🇭" },
  { text: "Bangladesh", id: "BD", icon: "🇧🇩" },
  { text: "Belarus", id: "BY", icon: "🇧🇾" },
  { text: "Belgium", id: "BE", icon: "🇧🇪" },
  { text: "Belize", id: "BZ", icon: "🇧🇿" },
  { text: "Benin", id: "BJ", icon: "🇧🇯" },
  { text: "Bhutan", id: "BT", icon: "🇧🇹" },
  { text: "Bolivia", id: "BO", icon: "🇧🇴" },
  { text: "Bosnia and Herzegovina", id: "BA", icon: "🇧🇦" },
  { text: "Botswana", id: "BW", icon: "🇧🇼" },
  { text: "Brazil", id: "BR", icon: "🇧🇷" },
  { text: "Brunei", id: "BN", icon: "🇧🇳" },
  { text: "Bulgaria", id: "BG", icon: "🇧🇬" },
  { text: "Cambodia", id: "KH", icon: "🇰🇭" },
  { text: "Cameroon", id: "CM", icon: "🇨🇲" },
  { text: "Canada", id: "CA", icon: "🇨🇦" },
  { text: "Chile", id: "CL", icon: "🇨🇱" },
  { text: "China", id: "CN", icon: "🇨🇳" },
  { text: "Colombia", id: "CO", icon: "🇨🇴" },
  { text: "Costa Rica", id: "CR", icon: "🇨🇷" },
  { text: "Croatia", id: "HR", icon: "🇭🇷" },
  { text: "Cuba", id: "CU", icon: "🇨🇺" },
  { text: "Cyprus", id: "CY", icon: "🇨🇾" },
  { text: "Czech Republic", id: "CZ", icon: "🇨🇿" },
  { text: "Denmark", id: "DK", icon: "🇩🇰" },
  { text: "Dominican Republic", id: "DO", icon: "🇩🇴" },
  { text: "Ecuador", id: "EC", icon: "🇪🇨" },
  { text: "Egypt", id: "EG", icon: "🇪🇬" },
  { text: "Estonia", id: "EE", icon: "🇪🇪" },
  { text: "Finland", id: "FI", icon: "🇫🇮" },
  { text: "France", id: "FR", icon: "🇫🇷" },
  { text: "Georgia", id: "GE", icon: "🇬🇪" },
  { text: "Germany", id: "DE", icon: "🇩🇪" },
  { text: "Ghana", id: "GH", icon: "🇬🇭" },
  { text: "Greece", id: "GR", icon: "🇬🇷" },
  { text: "Hong Kong", id: "HK", icon: "🇭🇰" },
  { text: "Hungary", id: "HU", icon: "🇭🇺" },
  { text: "Iceland", id: "IS", icon: "🇮🇸" },
  { text: "India", id: "IN", icon: "🇮🇳" },
  { text: "Indonesia", id: "ID", icon: "🇮🇩" },
  { text: "Iran", id: "IR", icon: "🇮🇷" },
  { text: "Iraq", id: "IQ", icon: "🇮🇶" },
  { text: "Ireland", id: "IE", icon: "🇮🇪" },
  { text: "Israel", id: "IL", icon: "🇮🇱" },
  { text: "Italy", id: "IT", icon: "🇮🇹" },
  { text: "Japan", id: "JP", icon: "🇯🇵" },
  { text: "Jordan", id: "JO", icon: "🇯🇴" },
  { text: "Kazakhstan", id: "KZ", icon: "🇰🇿" },
  { text: "Kenya", id: "KE", icon: "🇰🇪" },
  { text: "South Korea", id: "KR", icon: "🇰🇷" },
  { text: "Kuwait", id: "KW", icon: "🇰🇼" },
  { text: "Kyrgyzstan", id: "KG", icon: "🇰🇬" },
  { text: "Laos", id: "LA", icon: "🇱🇦" },
  { text: "Latvia", id: "LV", icon: "🇱🇻" },
  { text: "Lebanon", id: "LB", icon: "🇱🇧" },
  { text: "Libya", id: "LY", icon: "🇱🇾" },
  { text: "Lithuania", id: "LT", icon: "🇱🇹" },
  { text: "Luxembourg", id: "LU", icon: "🇱🇺" },
  { text: "Macau", id: "MO", icon: "🇲🇴" },
  { text: "Malaysia", id: "MY", icon: "🇲🇾" },
  { text: "Maldives", id: "MV", icon: "🇲🇻" },
  { text: "Malta", id: "MT", icon: "🇲🇹" },
  { text: "Mexico", id: "MX", icon: "🇲🇽" },
  { text: "Moldova", id: "MD", icon: "🇲🇩" },
  { text: "Mongolia", id: "MN", icon: "🇲🇳" },
  { text: "Montenegro", id: "ME", icon: "🇲🇪" },
  { text: "Morocco", id: "MA", icon: "🇲🇦" },
  { text: "Nepal", id: "NP", icon: "🇳🇵" },
  { text: "Netherlands", id: "NL", icon: "🇳🇱" },
  { text: "New Zealand", id: "NZ", icon: "🇳🇿" },
  { text: "Nigeria", id: "NG", icon: "🇳🇬" },
  { text: "Norway", id: "NO", icon: "🇳🇴" },
  { text: "Oman", id: "OM", icon: "🇴🇲" },
  { text: "Pakistan", id: "PK", icon: "🇵🇰" },
  { text: "Panama", id: "PA", icon: "🇵🇦" },
  { text: "Peru", id: "PE", icon: "🇵🇪" },
  { text: "Philippines", id: "PH", icon: "🇵🇭" },
  { text: "Poland", id: "PL", icon: "🇵🇱" },
  { text: "Portugal", id: "PT", icon: "🇵🇹" },
  { text: "Puerto Rico", id: "PR", icon: "🇵🇷" },
  { text: "Qatar", id: "QA", icon: "🇶🇦" },
  { text: "Romania", id: "RO", icon: "🇷🇴" },
  { text: "Russia", id: "RU", icon: "🇷🇺" },
  { text: "Saudi Arabia", id: "SA", icon: "🇸🇦" },
  { text: "Serbia", id: "RS", icon: "🇷🇸" },
  { text: "Singapore", id: "SG", icon: "🇸🇬" },
  { text: "Slovakia", id: "SK", icon: "🇸🇰" },
  { text: "Slovenia", id: "SI", icon: "🇸🇮" },
  { text: "South Africa", id: "ZA", icon: "🇿🇦" },
  { text: "Spain", id: "ES", icon: "🇪🇸" },
  { text: "Sri Lanka", id: "LK", icon: "🇱🇰" },
  { text: "Sweden", id: "SE", icon: "🇸🇪" },
  { text: "Switzerland", id: "CH", icon: "🇨🇭" },
  { text: "Syria", id: "SY", icon: "🇸🇾" },
  { text: "Taiwan", id: "TW", icon: "🇹🇼" },
  { text: "Tajikistan", id: "TJ", icon: "🇹🇯" },
  { text: "Thailand", id: "TH", icon: "🇹🇭" },
  { text: "Tunisia", id: "TN", icon: "🇹🇳" },
  { text: "Turkey", id: "TR", icon: "🇹🇷" },
  { text: "Turkmenistan", id: "TM", icon: "🇹🇲" },
  { text: "Ukraine", id: "UA", icon: "🇺🇦" },
  { text: "United Arab Emirates", id: "AE", icon: "🇦🇪" },
  { text: "United Kingdom", id: "GB", icon: "🇬🇧" },
  { text: "United States", id: "US", icon: "🇺🇸" },
  { text: "Uruguay", id: "UY", icon: "🇺🇾" },
  { text: "Uzbekistan", id: "UZ", icon: "🇺🇿" },
  { text: "Venezuela", id: "VE", icon: "🇻🇪" },
  { text: "Vietnam", id: "VN", icon: "🇻🇳" },
  { text: "Yemen", id: "YE", icon: "🇾🇪" },
  { text: "Zambia", id: "ZM", icon: "🇿🇲" },
  { text: "Zimbabwe", id: "ZW", icon: "🇿🇼" }
];